#include<iostream.h>
#include<conio.h>
#include<stdlib.h>
#include<graphics.h>
#include<string.h>

#define UP		1
#define RIGHT	2
#define DOWN	3
#define LEFT	4

#define Null	-5
#define NN		0
#define XX		1
#define OO		2
#define XH		11
#define OH		22
#define MOVING	33
#define MOVINGH	44
#define HH		99

#define BLACK	0
#define BLUE	1
#define GREEN	2
#define AQUA	3
#define RED	4
#define PURPLE	5
#define YELLOW	6
#define WHITE	7
#define GREY	8
#define LBLUE   9
#define LGREEN	10
#define LAQUA	11
#define LRED	12
#define LPURPLE	13
#define LYELLOW	14
#define BRIGHT	15

#define FIRSTGAMER 1
#define TOTALX 12
#define TOTALO 12

#include "C:\XO\Cell.H"
#include "C:\XO\Board.H"
